# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'customtkinter',
        'tkinterdnd2',
        'websockets',
        'aiohttp',
        'beautifulsoup4',
        'lxml',
        'rsa',
        'core',
        'core.agent',
        'core.command_executor',
        'core.account_manager',
        'core.config_manager',
        'core.ingestion_client',
        'core.mafile_scanner',
        'core.proxy_manager',
        'core.websocket_client',
        'gui',
        'gui.main_window',
        'gui.frames',
        'gui.frames.dashboard_frame',
        'gui.frames.accounts_frame',
        'gui.frames.settings_frame',
        'steampy',
        'steampy.client',
        'steampy.login',
        'steampy.guard',
        'steampy.market',
        'steampy.chat',
        'steampy.confirmation',
        'steampy.remote_client',
        'steampy.models',
        'steampy.utils',
        'steampy.exceptions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AutoBaseAgent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)

